live: 0
target_profit: 6000
stop_loss: -9999999
delta_threshold: 40
trailing_percent: 5
Update_EOD: 0
Past_M2M: 0
enter_today: 1
EntryType: AUTO
Expiry: 28-NOV-2024
lots: 1
lot_size: 75
min_strike_price: 23000
max_strike_price: 27000
nse_sym_path: NSE_symbols.txt
nfo_sym_path: NFO_symbols.txt
Symbol: NIFTY
