live: 0
positions_data: csv
percent_of_max_profit: 400
target_profit: 5000000
stop_loss: -5000000
enter_today: 0
enter_strategy: M
Update_EOD: 0
Past_M2M: 0
EntryType: AUTO
Expiry: 26-DEC-2024
BankExpiry: 24-DEC-2024
lots: 1
lot_size: 25
nse_sym_path: NSE_symbols.txt
nfo_sym_path: NFO_symbols.txt
Symbol: NIFTY
BankSymbol: BANKNIFTY
interval: 60
num_adjustments: 0
Entry_Date: '2024-11-23'
IFT: 50
ICT: 50
counter_test: 0
