live: 1
IC_delta_threshold: 40
IF_delta_threshold: 50
percent_profit: 10
target_profit: 10000
stop_loss: -10000
enter_today: 0
enable_trailing: 0
trailing_percent: 0
Update_EOD: 0
Past_M2M: 0
EntryType: AUTO
Expiry: 28-NOV-2024
lots: 1
lot_size: 75
min_strike_price: 21000
max_strike_price: 26000
nse_sym_path: NSE_symbols.txt
nfo_sym_path: NFO_symbols.txt
Symbol: NIFTY
interval: 60
iteration_hours: 3
num_adjustments: 0
Entry_Date: 2024-10-24
