live: 1
enable_trailing: 0
enter_today: 0
target_profit: 6950
stop_loss: -13900
delta_threshold: 40
trailing_percent: 5
Update_EOD: 1
Past_M2M: 0
EntryType: AUTO
Expiry: 28-NOV-2024
lots: 1
lot_size: 75
min_strike_price: 22000
max_strike_price: 27000
nse_sym_path: NSE_symbols.txt
nfo_sym_path: NFO_symbols.txt
Symbol: NIFTY
