live: 0
percent_of_max_profit: 50
target_profit: 5000000
stop_loss: -5000000
enter_today: 0
enable_trailing: 0
trailing_percent: 0
Update_EOD: 0
Past_M2M: 0
EntryType: AUTO
Expiry: 26-DEC-2024
lots: 6
lot_size: 75
min_strike_price: 21000
max_strike_price: 26000
nse_sym_path: NSE_symbols.txt
nfo_sym_path: NFO_symbols.txt
Symbol: NIFTY
interval: 60
num_adjustments: 0
Entry_Date: '2024-11-14'
start_time: 03:45:00
end_time: '20:00:00'
