name: Run Python Script every 5 mins

on:
  schedule:
    - cron: '45-59/5 3 * * 1-5'  # Runs from 9:15 AM to 9:55 AM on weekdays
    - cron: '*/5 4-9 * * 1-5'  # Runs every 5 minutes from 10:00 AM to 2:59 PM on weekdays
    - cron: '30-55/5 9 * * 1-5'  # Runs every 5 minutes from 3:00 PM to 3:25 PM on weekdays

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Run Python script
      run: python3 monitor.py
